language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="4.4.x-dev"
    - SS_BASE_URL="http://localhost:8080/"
    - SS_ENVIRONMENT_TYPE="dev"

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL
    - php: 7.2
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.composer/vendor/bin:$PATH
  - composer validate
  - composer require --no-update silverstripe/recipe-testing:^1 silverstripe/recipe-cms:4.4.x-dev
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
